name: PiPY Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Check version
        run: bash scripts/prepare_version.sh -v "${GITHUB_REF#refs/tags/}" -p gordo_core/_version.py

      - name : Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.3
        with:
          version: 1.2.2
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs

      - name: Build
        run: |
          poetry build -f wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PASSWORD }}
          packages-dir: dist/
